Some minor changes in README.md, English version added
approvers/is_odd_api pull request #5
Opened 2021-09-14 19:47 UTC by merunno

Please don't tell me you don't want the English version.

I give you permission to hit me in English.

2021-09-14 23:48 UTC, MikuroXina requested changes

2021-09-14 23:48 UTC, MikuroXina commented on README_EN.md
> +## 試す
```suggestion
## Try
```
英語になってないです.

2021-09-14 23:48 UTC, MikuroXina commented on README_EN.md
> +This API can determine even and odd numbers of Arabic numerals, double-byte Arabic numerals, Roman numerals, and Chinese numerals up to 1,000,000.
```suggestion
This API can determine even and odd numbers of Arabic numerals, full-width Arabic numerals, Roman numerals, and Chinese numerals up to 1,000,000.
```
「全角」の訳なら full-width が妥当かと.

2021-09-15 15:24 UTC, m1sk9 commented on README_EN.md
> +## 試す
Oh, なんてことだここあとでやります

2021-09-15 15:24 UTC, MikuroXina approved these changes

2021-09-15 15:24 UTC, merged